

on_hear("open sesame", "opensesame")
    {
    has_level(20)
        {
        narate("A section of the rock face to the east magically reforms itself to provide a cave entrance."
        add_exit(east, "theive's den")
        in(20)
            {
            narrate("The cave entrance shimmers and vanishes.")
            remove_exit(east)
            }
        }
    else
        {
        hint("Nothing happens.  Perhaps when you are older, ${name}.")
        }
    }


